### ISSUE TITLE
Generar Resumen de Base de Datos 

### ISSUE THREAD

**Issue by Tomyc1** [hpassera/aula12-grupo1#2]
Recompilar información de lo estudiado de base de datos, ya sea mediante links, glosarios o canales recomendados.

**Comment by MatCsantana** [comment]
Base de datos definida
Una base de datos es una recopilación organizada de información o datos estructurados, que normalmente se almacena de forma electrónica en un sistema informático. Normalmente, una base de datos está controlada por un [sistema de gestión de bases de datos (DBMS)](https://www.oracle.com/ar/database/what-is-database/#WhatIsDBMS). En conjunto, los datos y el DBMS, junto con las aplicaciones asociadas a ellos, reciben el nombre de sistema de bases de datos, abreviado normalmente a simplemente base de datos.

Los datos de los tipos más comunes de bases de datos en funcionamiento actualmente se suelen utilizar como estructuras de filas y columnas en una serie de tablas para aumentar la eficacia del procesamiento y la consulta de datos. Así, se puede acceder, gestionar, modificar, actualizar, controlar y organizar fácilmente los datos. La mayoría de las bases de datos utilizan un lenguaje de consulta estructurada (SQL) para escribir y consultar datos.

Evolución de la base de datos
Las bases de datos han evolucionado drásticamente desde su inicio a principios de la década de 1960. Las bases de datos de navegación, como la base de datos jerárquica (que se basaba en un modelo de árbol y permitía una relación de uno a muchos) y la base de datos de red (un modelo más flexible que permitía relaciones múltiples), eran los sistemas originales que se utilizaban para almacenar y manipular datos. Aunque eran sencillos, estos primeros sistemas eran inflexibles. En la década de 1980, se hicieron populares las [bases de datos relacionales](https://www.oracle.com/ar/database/what-is-database/#relational), seguidas de las [bases de datos orientadas a objetos](https://www.oracle.com/ar/database/what-is-database/#object-oriented) en la década de 1990. Más recientemente, las [bases de datos NoSQL](https://www.oracle.com/ar/database/what-is-database/#nosql) surgieron como respuesta al crecimiento de Internet y la necesidad de acelerar la velocidad y el procesamiento de los datos no estructurados. Hoy en día, las [bases de datos en la nube](https://www.oracle.com/ar/database/what-is-database/#cloud) y las [bases de datos de autogestión](https://www.oracle.com/ar/database/what-is-database/#autonomous) están abriendo nuevos horizontes en lo que respecta a la forma en la que se recopilan, se almacenan, se gestionan y se utilizan los datos.

¿Cuál es la diferencia entre una base de datos y una hoja de cálculo?
Tanto las bases de datos como las hojas de cálculo (como Microsoft Excel) son modos cómodos de almacenar información. Las principales diferencias entre los dos son:

Cómo se almacenan y se manipulan los datos
Quién puede acceder a los datos
Cuántos datos pueden almacenarse
Las hojas de cálculo se diseñaron originalmente para un usuario y sus características así lo reflejan. Son perfectas para un único usuario o para un pequeño número de usuarios que no necesiten hacer una gran manipulación de datos increíblemente complicada. Las bases de datos, por otro lado, están diseñadas para contener recopilaciones mucho más grandes de información organizada, a veces en cantidades masivas. Las bases de datos permiten que muchos usuarios accedan y consulten los datos de forma rápida y segura al mismo tiempo mediante una lógica y un lenguaje muy complejos.

Tipos de bases de datos
Existen muchos tipos diferentes de bases de datos. La mejor base de datos para una organización específica depende de cómo pretenda la organización utilizar los datos.

Bases de datos relacionales. Las bases de datos se hicieron predominantes en la década de 1980. Los elementos de una base de datos relacional se organizan como un conjunto de tablas con columnas y filas. La tecnología de bases de datos relacionales proporciona la forma más eficiente y flexible de acceder a información estructurada.
Bases de datos orientadas a objetos. La información de una base de datos orientada a objetos se representa en forma de objetos, como en la programación orientada a objetos.
Bases de datos distribuidas. Una base de datos distribuida consta de dos o más archivos que se encuentran en sitios diferentes. La base de datos puede almacenarse en varios ordenadores, ubicarse en la misma ubicación física o repartirse en diferentes redes.
Almacenes de datos. Un repositorio central de datos, un data warehouse es un tipo de base de datos diseñado específicamente para consultas y análisis rápidos.
Bases de datos NoSQL. Una base de datos [NoSQL](https://www.oracle.com/ar/database/nosql-cloud.html), o base de datos no relacional, permite almacenar y manipular datos no estructurados y semiestructurados (a diferencia de una base de datos relacional, que define cómo se deben componer todos los datos insertados en la base de datos). Las bases de datos NoSQL se hicieron populares a medida que las aplicaciones web se volvían más comunes y complejas.
Bases de datos orientadas a grafos. Una base de datos orientada a grafos almacena datos relacionados con entidades y las relaciones entre entidades.
Bases de datos OLTP. Una base de datos OLTP es una base de datos rápida y analítica diseñada para que muchos usuarios realicen un gran número de transacciones.
Estos son solo algunos de las varias docenas de tipos de bases de datos que se utilizan hoy en día. Otras bases de datos menos comunes se adaptan a funciones científicas, financieras o de otro tipo muy específicas. Además de los diferentes tipos de bases de datos, los cambios en los enfoques de desarrollo tecnológico y los avances considerables, como la nube y la automatización, están impulsando a las bases de datos en direcciones completamente nuevas. Algunas de las bases de datos más recientes incluyen

Bases de datos de código abierto. Un sistema de base de datos de código abierto es aquel cuyo código fuente es de código abierto; tales bases de datos pueden ser bases de datos SQL o NoSQL.
Bases de datos en la nube. Una [base de datos en la nube](https://www.oracle.com/ar/database/what-is-a-cloud-database/) es una recopilación de datos, estructurados o no estructurados, que reside en una plataforma de cloud computing privada, pública o híbrida. Existen dos tipos de modelos de bases de datos en la nube: tradicional y base de datos como servicio (DBaaS). Con DBaaS, un proveedor de servicios realiza las tareas administrativas y el mantenimiento.
Base de datos multimodelo. Las bases de datos multimodelo combinan distintos tipos de modelos de bases de datos en un único servidor integrado. Esto significa que pueden incorporar diferentes tipos de datos.
Bases de datos de documentos/JSON. Diseñadas para almacenar, recuperar y gestionar información orientada a los documentos, las bases de datos de documentos son una forma moderna de almacenar los datos en formato JSON en lugar de en filas y columnas.
Bases de datos de autogestión. El tipo de base de datos más nuevo e innovador, las bases de datos de autogestión (también conocidas como bases de datos autónomas) están basadas en la nube y utilizan el machine learning para automatizar el ajuste de la base de datos, la seguridad, las copias de seguridad, las actualizaciones y otras tareas de gestión rutinarias que tradicionalmente realizan los administradores de bases de datos.
[Más información sobre las bases de datos de autogestión](https://www.oracle.com/ar/database/what-is-autonomous-database.html)
¿Qué es un software de base de datos?
El software de base de datos se utiliza para crear, editar y mantener archivos y registros de bases de datos, lo que facilita la creación de archivos y registros, la entrada de datos, la edición de datos, la actualización y la creación de informes. El software también maneja el almacenamiento de datos, las copias de seguridad y la creación de informes, así como el control de acceso múltiple y la seguridad. La seguridad sólida de las bases de datos es especialmente importante hoy en día, ya que el robo de datos es cada vez más frecuente. En ocasiones, el software de base de datos también se denomina "sistema de gestión de bases de datos" (DBMS).

El software de base de datos simplifica la gestión de datos, ya que permite a los usuarios almacenar datos de forma estructurada y acceder posteriormente a ellos. Por lo general, tiene una interfaz gráfica que ayuda a crear y administrar los datos y, en algunos casos, los usuarios pueden [construir sus propias bases de datos](https://www.oracle.com/ar/autonomous-database/) mediante el uso de software de base de datos.

¿Qué es un sistema de gestión de bases de datos (DBMS)?
Normalmente, una base de datos requiere un programa de software de bases de datos completo, conocido como sistema de gestión de bases de datos (DBMS). Un DBMS sirve como interfaz entre la base de datos y sus programas o usuarios finales, lo que permite a los usuarios recuperar, actualizar y gestionar cómo se organiza y se optimiza la información. Un DBMS también facilita la supervisión y el control de las bases de datos, lo que permite una variedad de operaciones administrativas como la supervisión del rendimiento, el ajuste, la copia de seguridad y la recuperación.

Algunos ejemplos de software de bases de datos o DBMS populares incluyen MySQL, Microsoft Access, Microsoft SQL Server, FileMaker Pro, Oracle Database y dBASE.

¿Qué es una base de datos MySQL?
MySQL es un sistema de gestión de bases de datos relacionales de código abierto basado en SQL. Se diseñó y se optimizó para las aplicaciones web y puede utilizarse en cualquier plataforma. A medida que surgían nuevos y diferentes requisitos con Internet, MySQL se convirtió en la plataforma preferida por los desarrolladores web y las aplicaciones basadas en web. Dado que está diseñado para procesar millones de consultas y miles de transacciones, MySQL es una elección popular para las empresas de comercio electrónico que necesitan gestionar múltiples transferencias de dinero. La flexibilidad on-demand es la principal función de MySQL.

MySQL es el DBMS que se encuentra detrás de algunos de los sitios web y aplicaciones basadas en web más importantes del mundo, como Airbnb, Uber, LinkedIn, Facebook, Twitter y YouTube.

[Más información sobre MySQL](https://www.oracle.com/ar/mysql/)
Uso de bases de datos para mejorar el rendimiento del negocio y la toma de decisiones
Con la recopilación masiva de datos del Internet of Things que está transformando la vida y la industria en todo el mundo, las empresas de hoy en día tienen acceso a más datos que nunca. Las empresas visionarias ahora pueden utilizar las bases de datos para ir más allá del almacenamiento básico de datos y las transacciones con el fin de analizar grandes cantidades de datos de múltiples sistemas. Mediante el uso de bases de datos y otras herramientas informáticas y de inteligencia empresarial, las organizaciones ahora pueden aprovechar los datos que recopilan para funcionar de forma más eficiente, permitir una mejor toma de decisiones y ser más ágiles y escalables.

La base de datos de autogestión está preparada para proporcionar un impulso significativo a estas capacidades. Dado que las bases de datos de autogestión automatizan procesos manuales costosos y tediosos, liberan a los usuarios empresariales para que puedan ser más proactivos con sus datos. Al tener control directo sobre la capacidad de crear y utilizar bases de datos, los usuarios ganan control y autonomía al mismo tiempo que mantienen importantes estándares de seguridad.

Desafíos de las bases de datos
Las bases de datos de las grandes empresas de hoy en día soportan a menudo consultas muy complejas y se espera que proporcionen respuestas casi instantáneas a esas consultas. En consecuencia, se solicita a los administradores de bases de datos que empleen una amplia variedad de métodos para ayudar a mejorar el rendimiento. Algunos desafíos comunes a los que se enfrentan incluyen:

Absorción de aumentos significativos en el volumen de datos. La explosión de datos provenientes de sensores, máquinas conectadas y docenas de otras fuentes hace que los administradores de bases de datos tengan que luchar para administrar y organizar los datos de sus empresas’ de manera eficiente.
Garantía de seguridad de los datos. Actualmente, se producen filtraciones de datos en todas partes, y los piratas informáticos son cada vez más ingeniosos. Garantizar que los datos estén seguros es más importante que nunca, pero también que los usuarios puedan acceder a ellos fácilmente.
Mantenimiento al día con la demanda. En el entorno empresarial actual de rápido crecimiento, las empresas necesitan tener acceso en tiempo real a sus datos para poder tomar decisiones a tiempo y aprovechar las nuevas oportunidades.
Gestión y mantenimiento de la base de datos y la infraestructura. Los administradores de bases de datos deben supervisar continuamente la base de datos por si surgen problemas y realizar un mantenimiento preventivo, así como aplicar parches y actualizaciones de software. A medida que las bases de datos se hacen más complejas y los volúmenes de datos crecen, las empresas se enfrentan a los gastos de contratar talentos adicionales para supervisar y ajustar sus bases de datos.
Eliminación de los límites de la escalabilidad. Un negocio necesita crecer si quiere sobrevivir, y su gestión de datos debe crecer con él. No obstante, para los administradores de bases de datos resulta muy difícil predecir cuánta capacidad necesitará la empresa, especialmente con las bases de datos on-premise.
Abordar todos estos desafíos puede requerir mucho tiempo y puede impedir que los administradores de bases de datos realicen funciones más estratégicas.

Cómo mejora la tecnología autónoma la gestión de bases de datos
Las bases de datos de autogestión son la ola del futuro y ofrecen una posibilidad fascinante para las organizaciones que deseen utilizar la mejor tecnología de bases de datos disponible sin los problemas que supone ejecutar y utilizar esa tecnología.

Las bases de datos de autogestión utilizan una tecnología basada en la nube y el machine learning para automatizar muchas de las tareas rutinarias necesarias para gestionar bases de datos, como el ajuste, la seguridad, las copias de seguridad, las actualizaciones y otras tareas de gestión rutinarias. Al automatizar estas tediosas tareas, los administradores de bases de datos se quedan libres para realizar un trabajo más estratégico. Las funciones de autogestión, autoprotección y autorreparación de las bases de datos de autogestión están preparadas para revolucionar la forma de gestionar y proteger los datos de las empresas, lo que permite obtener ventajas de rendimiento, reducir costes y mejorar la seguridad.

Futuro de las bases de datos y las bases de datos autónomas
La [primera base de datos autónoma](https://www.oracle.com/ar/database/what-is-database/?bcid=5632300155001&shareURL=https://video.oracle.com/detail/video/5632300155001) se anunció a finales de 2017 y muchos analistas independientes de la industria reconocieron rápidamente la tecnología y su impacto potencial en la informática.

La [perspectiva de IDC de febrero de 2018](http://idcdocserv.com/US43571317) elogió la tecnología de base de datos autónoma para hacer que el “software empresarial sea más fácil de implementar, utilizar y administrar, gracias al uso de la inteligencia artificial y el machine learning para proporcionar capacidades que requieren poca o ninguna intervención humana para gestionar el software.”

El informe de [KuppingerCole de enero de 2018 (PDF)](https://www.oracle.com/ar/a/ocom/docs/kuppingercole-autonomous-database-4368706.pdf) afirmaba que “este enfoque tiene enormes beneficios potenciales, no solo para reducir la mano de obra y los costes para los clientes, sino para mejorar drásticamente la resistencia de las bases de datos’ tanto frente a los errores humanos como frente a las actividades maliciosas, internas o externas. Cada base de datos también está diseñada para tener características de seguridad habilitadas de manera predeterminada y parámetros relevantes configurados automáticamente de acuerdo con las mejores prácticas de seguridad [actuales.”[](url)]([url]([url](url)))
