### ISSUE TITLE
Recompilar información de Scrum 

### ISSUE THREAD

**Issue by Tomyc1** [hpassera/aula12-grupo1#4]
Se va a recompilar todo lo estudiado en scrum, mediante enlaces, glosario y canales recomendados.

**Comment by Julimartins** [comment]
Trabajando en esto

**Comment by MatCsantana** [comment]
Trabajare en eso.

**Comment by Julimartins** [comment]
> Trabajare en eso.

No ví que hayas puesto nada. Ahora completo yo el resumen de esta tarea

**Comment by Julimartins** [comment]
Conceptos de Scrum
Definición de Scrum
Scrum: Es un marco de trabajo a través
del cual las personas pueden abordar
problemas complejos adaptativos, a la vez
que se entregan productos de forma
eficiente y creativa con el máximo valor.

Caracteristicas del Scrum
Es un enfoque ágil para la gestión de un proyecto. Más que una
metodología o proceso, es un Marco de Trabajo.
- Utiliza procesos interactivos/incrementales.
- Orientado a resultados y compromisos.
- No está restringido a proyectos de software solamente.
- Su visión es opuesta a la propuesta por la metodología en
cascada.

Pilares
- El ciclo de vida iterativo e incremental (Sprint)
- La comunicación.
- Transparencia:
Los aspectos significativos del proceso deben ser visibles para todos aquellos que son responsables del resultado. La
transparencia requiere que dichos aspectos sean definidos en base a un estándar común, de tal modo que los
observadores compartan un entendimiento común de lo que se están viendo.
Por ejemplo
Deben compartir un lenguaje común todos los participantes para referirse al proceso; y,
Aquellos que desempeñan el trabajo y quienes inspeccionan el incremento resultante deben compartir una definición
común de “Terminado” (“Done”).
- Inspección:
Los usuarios de Scrum deben inspeccionar frecuentemente los Artefactos de Scrum y el progreso hacia un objetivo para
detectar variaciones indeseadas. Su inspección no debe ser tan frecuente como para que pueda interferir en el trabajo.
Las inspecciones son más beneficiosas cuando se realizan de forma diligente por inspectores expertos en el mismo
lugar de trabajo.
- Adaptación:
Si un inspector determina que uno o más aspectos de un proceso se desvían de los límites aceptables y que el producto
resultante será inaceptable, el proceso o el material que está siendo procesado deben ajustarse. Dicho ajuste deberá
realizarse cuanto antes para minimizar desviaciones mayores.


¿ Que es un Sprint ?
El Sprint es un período de corta duración que debe finalizar con un prototipo
operativo o producto parcialmente entregable. El mismo se repite n veces a
lo largo del proyecto y permite hacer entregas de producto en partes, donde
cada entrega, es un incremento de funcionalidad respecto al anterior. Esto
difiere del conocido ciclo de vida en cascada muy utilizado en el campo de
desarrollo de software en que, las fases del ciclo de vida (requisitos, análisis,
diseño, codificación, testing, etc.) se realizan una única vez y, el inicio de
cada fase no comienza hasta que termina la que precede.




### Roles en la metodologia Scrum

- Product owner : Representante de los accionistas y clientes que usan el software. Se focaliza en la parte de negocio y él es responsable del ROI (Return On Investment) del proyecto (entregar un valor superior al dinero invertido). Traslada la visión del proyecto al equipo, formaliza las prestaciones en historias a incorporar en el Product Backlog y las prioriza de forma regular.
- Scrum master:Es la persona que lidera al equipo, guiándolo para que cumpla las reglas y procesos de la metodología. Además gestiona la reducción de impedimentos del proyecto y trabaja con el Product Owner para maximizar el ROI (Return On Investment).
-Team: Grupo de profesionales con los conocimientos técnicos necesarios y que desarrollan el proyecto de manera conjunta llevando a cabo las historias a las que se comprometen al inicio de cada sprint.

 Ceremonias que se realizan a lo largo del proyecto:
- Sprint Planning Meeting
 > (reunión de planificación del sprint). Se produce al iniciar cada
Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.

- Daily Scrum Meeting
 >  (reunión periódica). Se produce diariamente, y tiene un máximo de
20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y
qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.
- Sprint Review Meeting
 >  (reunión de revisión del Sprint). Se produce al finalizar el Sprint y
tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el
Product Owner.
- Sprint Retrospective Meeting
>  (reunión de retrospectiva del Sprint). Se produce también al
finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado
en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que
debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.

Artefactos de Scrum
 
 En el marco de trabajo Scrum, denominamos Artefacto a aquellos elementos físicos que se producen como resultado de la aplicación de Scrum. Los tres principales artefactos o herramientas Scrum son: el Product Backlog, Sprint Backlog y el Incremento.
 
Incremento :
 Si Scrum tuviera que ser reducido a una sola cosa, sería a entregar una pieza de software terminado en cada Sprint. Un Incremento es el resultado del Sprint, es la suma de todas las tareas, casos de uso, historias de usuario y cualquier elemento que se haya desarrollado durante el Sprint y que será puesto a disposición del usuario final en forma de software, aportando un valor de negocio al producto que se está desarrollando.
Construir software de manera ágil se basa en hacerlo de manera iterativa e incremental. Mediante las iteraciones, nos aseguramos que todo el ciclo de vida del software (planificación, diseño, desarrollo, testeo y entrega) ocurre en 4 semanas o menos. Por supuesto, no podemos construir toda la funcionalidad que queremos en solo cuatro semanas y tenemos que buscar la manera de ir entregando los componentes necesarios justo a tiempo.

Product Backlog :
El Product Backlog es un inventario que contiene cualquier tipo de trabajo que haya que hacer en el producto: requerimientos, casos de uso, tareas y dependencias. Es la principal fuente de información sobre el producto en Scrum, una lista, en cualquier formato, que contiene todos los requerimientos que necesitamos implementar en el producto.
Esta lista es el resultado del trabajo del Product Owner con el cliente, los distintos stakeholders, sponsors, comités, etc, y refleja el estado real del trabajo pendiente de implementar en el producto, así como el ya realizado.
El Product Backlog debe ser gestionado en exclusiva por el Product Owner, siendo su principal función la de priorizar aquellos elementos que tienen más valor en cada etapa y detallarlos para que el equipo de desarrollo sea capaz de valorarlos y ejecutarlos.

 Sprint Backlog :

Se trata de una lista de elementos en los que trabajar durante la etapa de Sprint. Estos elementos normalmente se componen de tareas técnicas más pequeñas que permiten conseguir un incremento de software terminado.
Todo el trabajo que el Development Team haya seleccionado para hacer durante el siguiente Sprint pasa al Sprint Backlog. Este artefacto es un elemento para visualizar el trabajo a realizar durante cada Sprint y está gestionado por el equipo de desarrollo. Su propósito es mantener la transparencia dentro del desarrollo, actualizándolo durante toda la iteración especialmente a través de los daily Scrums.
