### ISSUE TITLE
Recopilación  de Material de Estudios de Ética Y Deontologia Profesional 

### ISSUE THREAD

**Issue by Tomyc1** [hpassera/aula12-grupo1#5]
Recompilar información de lo estudiado de Ética y Deontología Profesional , ya sea mediante links, glosarios o canales recomendados.

**Comment by roxyOlivares32** [comment]
GLOSARIO
                                             
                                                Ética y Deontologia Profesional

 •	Ética:  es una disciplina filosófica que se define como "principios directivos que orientan a las personas en cuanto a la concepción de la vida, el hombre, los juicios, los hechos, y la moral”. Búsqueda del bien, de la realización personal en armonía con los seres humanos e implica una relación dinámica entre nuestros valores y los de la sociedad que nos haya tocado vivir, tiende a ser una postura personal e intima adoptada por cada individuo según sus principios.
•	Ética informática: Se define "como la disciplina que analiza los problemas éticos que son creados por la tecnología de los ordenadores o también los que son transformados o agravados por la misma". Es decir, por las personas que utilizan los avances de las tecnologías de la información .
•	 Moral: Se refiere a los códigos de normas impuestos por una sociedad para regular la conducta o el comportamiento de los individuos. Abarca reglas tradiciones y valores compartidas por una sociedad en determinado momento de su historia. La moral tiende a ser normativa a reflejarse en reglamentos y prohibiciones, como algunos preceptos.



                                   DILEMA EN LAS REDES SOCIALES 

El filme describe la adicción y los impactos negativos de las redes sociales en personas y comunidades, como resultado de las estrategias diseñadas para manipular emociones y comportamientos, y mantener conectados a los usuarios.


https://cuevana.se/pelicula/el-dilema-de-las-redes-sociales/[](url)
[https://www.netflix.com/ar/title/81254224](url)
